module LegalesignSDK
  module Resources
    class Templatepdf
      class Fields
        def create: (
          String pdf_id,
          body: ::Array[LegalesignSDK::Templatepdf::FieldCreateParams::Body],
          ?request_options: LegalesignSDK::request_opts
        ) -> nil

        def list: (
          String pdf_id,
          ?request_options: LegalesignSDK::request_opts
        ) -> LegalesignSDK::Models::Templatepdf::FieldListResponse

        def initialize: (client: LegalesignSDK::Client) -> void
      end
    end
  end
end
