module LegalesignSDK
  module Resources
    class Status
      def retrieve: (
        String doc_id,
        ?request_options: LegalesignSDK::request_opts
      ) -> LegalesignSDK::Models::StatusRetrieveResponse

      def initialize: (client: LegalesignSDK::Client) -> void
    end
  end
end
