module LegalesignSDK
  module Models
    type signer_retrieve_params =
      {  } & LegalesignSDK::Internal::Type::request_parameters

    class SignerRetrieveParams < LegalesignSDK::Internal::Type::BaseModel
      extend LegalesignSDK::Internal::Type::RequestParameters::Converter
      include LegalesignSDK::Internal::Type::RequestParameters

      def initialize: (?request_options: LegalesignSDK::request_opts) -> void

      def to_hash: -> { request_options: LegalesignSDK::RequestOptions }
    end
  end
end
