module Legalesign
  module Models
    type invited_delete_params =
      {  } & Legalesign::Internal::Type::request_parameters

    class InvitedDeleteParams < Legalesign::Internal::Type::BaseModel
      extend Legalesign::Internal::Type::RequestParameters::Converter
      include Legalesign::Internal::Type::RequestParameters

      def initialize: (?request_options: Legalesign::request_opts) -> void

      def to_hash: -> { request_options: Legalesign::RequestOptions }
    end
  end
end
