module Legalesign
  module Models
    type list_meta =
      {
        limit: Integer,
        next_: String?,
        offset: Integer,
        previous: String?,
        total_count: Integer
      }

    class ListMeta < Legalesign::Internal::Type::BaseModel
      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_accessor next_: String?

      attr_reader offset: Integer?

      def offset=: (Integer) -> Integer

      attr_accessor previous: String?

      attr_reader total_count: Integer?

      def total_count=: (Integer) -> Integer

      def initialize: (
        ?limit: Integer,
        ?next_: String?,
        ?offset: Integer,
        ?previous: String?,
        ?total_count: Integer
      ) -> void

      def to_hash: -> {
        limit: Integer,
        next_: String?,
        offset: Integer,
        previous: String?,
        total_count: Integer
      }
    end
  end
end
