module Legalesign
  module Models
    type pdf_field_validation_enum =
      1
      | 2
      | 3
      | 4
      | 5
      | 6
      | 7
      | 8
      | 9
      | 10
      | 11
      | 12
      | 13
      | 14
      | 15
      | 16
      | 17
      | 18
      | 19
      | 20
      | 24
      | 25
      | 26
      | 30
      | 31
      | 32
      | 33
      | 34
      | 35
      | 36
      | 37
      | 38
      | 39
      | 40
      | 41
      | 42
      | 43
      | 44
      | 45
      | 46
      | 47
      | 48
      | 50
      | 51
      | 52
      | 53
      | 54
      | 55
      | 56
      | 57
      | 58
      | 59
      | 60
      | 61
      | 62
      | 63
      | 64
      | 65
      | 66
      | 67
      | 68
      | 69
      | 70
      | 71
      | 72
      | 73
      | 74
      | 75
      | 76
      | 77
      | 78
      | 79
      | 80
      | 81
      | 82
      | 83
      | 84
      | 85
      | 90
      | 91
      | 92

    module PdfFieldValidationEnum
      extend Legalesign::Internal::Type::Enum

      PDF_FIELD_VALIDATION_ENUM_1: 1
      PDF_FIELD_VALIDATION_ENUM_2: 2
      PDF_FIELD_VALIDATION_ENUM_3: 3
      PDF_FIELD_VALIDATION_ENUM_4: 4
      PDF_FIELD_VALIDATION_ENUM_5: 5
      PDF_FIELD_VALIDATION_ENUM_6: 6
      PDF_FIELD_VALIDATION_ENUM_7: 7
      PDF_FIELD_VALIDATION_ENUM_8: 8
      PDF_FIELD_VALIDATION_ENUM_9: 9
      PDF_FIELD_VALIDATION_ENUM_10: 10
      PDF_FIELD_VALIDATION_ENUM_11: 11
      PDF_FIELD_VALIDATION_ENUM_12: 12
      PDF_FIELD_VALIDATION_ENUM_13: 13
      PDF_FIELD_VALIDATION_ENUM_14: 14
      PDF_FIELD_VALIDATION_ENUM_15: 15
      PDF_FIELD_VALIDATION_ENUM_16: 16
      PDF_FIELD_VALIDATION_ENUM_17: 17
      PDF_FIELD_VALIDATION_ENUM_18: 18
      PDF_FIELD_VALIDATION_ENUM_19: 19
      PDF_FIELD_VALIDATION_ENUM_20: 20
      PDF_FIELD_VALIDATION_ENUM_24: 24
      PDF_FIELD_VALIDATION_ENUM_25: 25
      PDF_FIELD_VALIDATION_ENUM_26: 26
      PDF_FIELD_VALIDATION_ENUM_30: 30
      PDF_FIELD_VALIDATION_ENUM_31: 31
      PDF_FIELD_VALIDATION_ENUM_32: 32
      PDF_FIELD_VALIDATION_ENUM_33: 33
      PDF_FIELD_VALIDATION_ENUM_34: 34
      PDF_FIELD_VALIDATION_ENUM_35: 35
      PDF_FIELD_VALIDATION_ENUM_36: 36
      PDF_FIELD_VALIDATION_ENUM_37: 37
      PDF_FIELD_VALIDATION_ENUM_38: 38
      PDF_FIELD_VALIDATION_ENUM_39: 39
      PDF_FIELD_VALIDATION_ENUM_40: 40
      PDF_FIELD_VALIDATION_ENUM_41: 41
      PDF_FIELD_VALIDATION_ENUM_42: 42
      PDF_FIELD_VALIDATION_ENUM_43: 43
      PDF_FIELD_VALIDATION_ENUM_44: 44
      PDF_FIELD_VALIDATION_ENUM_45: 45
      PDF_FIELD_VALIDATION_ENUM_46: 46
      PDF_FIELD_VALIDATION_ENUM_47: 47
      PDF_FIELD_VALIDATION_ENUM_48: 48
      PDF_FIELD_VALIDATION_ENUM_50: 50
      PDF_FIELD_VALIDATION_ENUM_51: 51
      PDF_FIELD_VALIDATION_ENUM_52: 52
      PDF_FIELD_VALIDATION_ENUM_53: 53
      PDF_FIELD_VALIDATION_ENUM_54: 54
      PDF_FIELD_VALIDATION_ENUM_55: 55
      PDF_FIELD_VALIDATION_ENUM_56: 56
      PDF_FIELD_VALIDATION_ENUM_57: 57
      PDF_FIELD_VALIDATION_ENUM_58: 58
      PDF_FIELD_VALIDATION_ENUM_59: 59
      PDF_FIELD_VALIDATION_ENUM_60: 60
      PDF_FIELD_VALIDATION_ENUM_61: 61
      PDF_FIELD_VALIDATION_ENUM_62: 62
      PDF_FIELD_VALIDATION_ENUM_63: 63
      PDF_FIELD_VALIDATION_ENUM_64: 64
      PDF_FIELD_VALIDATION_ENUM_65: 65
      PDF_FIELD_VALIDATION_ENUM_66: 66
      PDF_FIELD_VALIDATION_ENUM_67: 67
      PDF_FIELD_VALIDATION_ENUM_68: 68
      PDF_FIELD_VALIDATION_ENUM_69: 69
      PDF_FIELD_VALIDATION_ENUM_70: 70
      PDF_FIELD_VALIDATION_ENUM_71: 71
      PDF_FIELD_VALIDATION_ENUM_72: 72
      PDF_FIELD_VALIDATION_ENUM_73: 73
      PDF_FIELD_VALIDATION_ENUM_74: 74
      PDF_FIELD_VALIDATION_ENUM_75: 75
      PDF_FIELD_VALIDATION_ENUM_76: 76
      PDF_FIELD_VALIDATION_ENUM_77: 77
      PDF_FIELD_VALIDATION_ENUM_78: 78
      PDF_FIELD_VALIDATION_ENUM_79: 79
      PDF_FIELD_VALIDATION_ENUM_80: 80
      PDF_FIELD_VALIDATION_ENUM_81: 81
      PDF_FIELD_VALIDATION_ENUM_82: 82
      PDF_FIELD_VALIDATION_ENUM_83: 83
      PDF_FIELD_VALIDATION_ENUM_84: 84
      PDF_FIELD_VALIDATION_ENUM_85: 85
      PDF_FIELD_VALIDATION_ENUM_90: 90
      PDF_FIELD_VALIDATION_ENUM_91: 91
      PDF_FIELD_VALIDATION_ENUM_92: 92

      def self?.values: -> ::Array[Legalesign::Models::pdf_field_validation_enum]
    end
  end
end
