module Legalesign
  module Models
    type signer_send_reminder_params =
      { text: String } & Legalesign::Internal::Type::request_parameters

    class SignerSendReminderParams < Legalesign::Internal::Type::BaseModel
      extend Legalesign::Internal::Type::RequestParameters::Converter
      include Legalesign::Internal::Type::RequestParameters

      attr_reader text: String?

      def text=: (String) -> String

      def initialize: (
        ?text: String,
        ?request_options: Legalesign::request_opts
      ) -> void

      def to_hash: -> {
        text: String,
        request_options: Legalesign::RequestOptions
      }
    end
  end
end
