module Legalesign
  module Models
    type template_retrieve_response =
      {
        archive: bool,
        created: Time,
        group: String,
        has_fields: bool,
        latest_text: String,
        modified: Time,
        resource_uri: String,
        signee_count: Integer,
        title: String,
        user: String,
        uuid: String
      }

    class TemplateRetrieveResponse < Legalesign::Internal::Type::BaseModel
      attr_reader archive: bool?

      def archive=: (bool) -> bool

      attr_reader created: Time?

      def created=: (Time) -> Time

      attr_reader group: String?

      def group=: (String) -> String

      attr_reader has_fields: bool?

      def has_fields=: (bool) -> bool

      attr_reader latest_text: String?

      def latest_text=: (String) -> String

      attr_reader modified: Time?

      def modified=: (Time) -> Time

      attr_reader resource_uri: String?

      def resource_uri=: (String) -> String

      attr_reader signee_count: Integer?

      def signee_count=: (Integer) -> Integer

      attr_reader title: String?

      def title=: (String) -> String

      attr_reader user: String?

      def user=: (String) -> String

      attr_reader uuid: String?

      def uuid=: (String) -> String

      def initialize: (
        ?archive: bool,
        ?created: Time,
        ?group: String,
        ?has_fields: bool,
        ?latest_text: String,
        ?modified: Time,
        ?resource_uri: String,
        ?signee_count: Integer,
        ?title: String,
        ?user: String,
        ?uuid: String
      ) -> void

      def to_hash: -> {
        archive: bool,
        created: Time,
        group: String,
        has_fields: bool,
        latest_text: String,
        modified: Time,
        resource_uri: String,
        signee_count: Integer,
        title: String,
        user: String,
        uuid: String
      }
    end
  end
end
