module Legalesign
  module Models
    type unsubscribe_delete_webhook_params =
      {
        url: String,
        event_filter: Legalesign::Models::webhook_event_filter_enum,
        group: Integer
      }
      & Legalesign::Internal::Type::request_parameters

    class UnsubscribeDeleteWebhookParams < Legalesign::Internal::Type::BaseModel
      extend Legalesign::Internal::Type::RequestParameters::Converter
      include Legalesign::Internal::Type::RequestParameters

      attr_accessor url: String

      attr_reader event_filter: Legalesign::Models::webhook_event_filter_enum?

      def event_filter=: (
        Legalesign::Models::webhook_event_filter_enum
      ) -> Legalesign::Models::webhook_event_filter_enum

      attr_reader group: Integer?

      def group=: (Integer) -> Integer

      def initialize: (
        url: String,
        ?event_filter: Legalesign::Models::webhook_event_filter_enum,
        ?group: Integer,
        ?request_options: Legalesign::request_opts
      ) -> void

      def to_hash: -> {
        url: String,
        event_filter: Legalesign::Models::webhook_event_filter_enum,
        group: Integer,
        request_options: Legalesign::RequestOptions
      }
    end
  end
end
