# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "legalesign_sdk/version"
require_relative "legalesign_sdk/internal/util"
require_relative "legalesign_sdk/internal/type/converter"
require_relative "legalesign_sdk/internal/type/unknown"
require_relative "legalesign_sdk/internal/type/boolean"
require_relative "legalesign_sdk/internal/type/file_input"
require_relative "legalesign_sdk/internal/type/enum"
require_relative "legalesign_sdk/internal/type/union"
require_relative "legalesign_sdk/internal/type/array_of"
require_relative "legalesign_sdk/internal/type/hash_of"
require_relative "legalesign_sdk/internal/type/base_model"
require_relative "legalesign_sdk/internal/type/base_page"
require_relative "legalesign_sdk/internal/type/request_parameters"
require_relative "legalesign_sdk/internal"
require_relative "legalesign_sdk/request_options"
require_relative "legalesign_sdk/file_part"
require_relative "legalesign_sdk/errors"
require_relative "legalesign_sdk/internal/transport/base_client"
require_relative "legalesign_sdk/internal/transport/pooled_net_requester"
require_relative "legalesign_sdk/client"
require_relative "legalesign_sdk/models/document_archive_params"
require_relative "legalesign_sdk/models/document_create_params"
require_relative "legalesign_sdk/models/document_create_response"
require_relative "legalesign_sdk/models/document_get_fields_params"
require_relative "legalesign_sdk/models/document_get_fields_response"
require_relative "legalesign_sdk/models/document_list_params"
require_relative "legalesign_sdk/models/document_list_response"
require_relative "legalesign_sdk/models/document_permanently_delete_params"
require_relative "legalesign_sdk/models/document_retrieve_params"
require_relative "legalesign_sdk/models/document_retrieve_response"
require_relative "legalesign_sdk/models/document_status_enum"
require_relative "legalesign_sdk/models/group_create_params"
require_relative "legalesign_sdk/models/group_list_params"
require_relative "legalesign_sdk/models/group_list_response"
require_relative "legalesign_sdk/models/group_retrieve_params"
require_relative "legalesign_sdk/models/group_retrieve_response"
require_relative "legalesign_sdk/models/list_meta"
require_relative "legalesign_sdk/models/pdf_field_validation_enum"
require_relative "legalesign_sdk/models/pdf_retrieve_params"
require_relative "legalesign_sdk/models/signer_get_access_link_params"
require_relative "legalesign_sdk/models/signer_retrieve_fields_params"
require_relative "legalesign_sdk/models/signer_retrieve_fields_response"
require_relative "legalesign_sdk/models/signer_retrieve_params"
require_relative "legalesign_sdk/models/signer_retrieve_response"
require_relative "legalesign_sdk/models/signer_send_reminder_params"
require_relative "legalesign_sdk/models/signer_status_enum"
require_relative "legalesign_sdk/models/status_retrieve_params"
require_relative "legalesign_sdk/models/status_retrieve_response"
require_relative "legalesign_sdk/models/template_create_params"
require_relative "legalesign_sdk/models/template_list_params"
require_relative "legalesign_sdk/models/template_list_response"
require_relative "legalesign_sdk/models/templatepdf/field_create_params"
require_relative "legalesign_sdk/models/templatepdf/field_list_params"
require_relative "legalesign_sdk/models/templatepdf/field_list_response"
require_relative "legalesign_sdk/models/template_pdf"
require_relative "legalesign_sdk/models/templatepdf_create_params"
require_relative "legalesign_sdk/models/templatepdf_get_edit_link_params"
require_relative "legalesign_sdk/models/templatepdf_get_edit_link_response"
require_relative "legalesign_sdk/models/templatepdf_list_params"
require_relative "legalesign_sdk/models/templatepdf_list_response"
require_relative "legalesign_sdk/models/templatepdf_retrieve_params"
require_relative "legalesign_sdk/models/template_retrieve_params"
require_relative "legalesign_sdk/models/template_retrieve_response"
require_relative "legalesign_sdk/models/template_update_params"
require_relative "legalesign_sdk/models"
require_relative "legalesign_sdk/resources/document"
require_relative "legalesign_sdk/resources/group"
require_relative "legalesign_sdk/resources/pdf"
require_relative "legalesign_sdk/resources/signer"
require_relative "legalesign_sdk/resources/status"
require_relative "legalesign_sdk/resources/template"
require_relative "legalesign_sdk/resources/templatepdf"
require_relative "legalesign_sdk/resources/templatepdf/fields"
