# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "legalesign/version"
require_relative "legalesign/internal/util"
require_relative "legalesign/internal/type/converter"
require_relative "legalesign/internal/type/unknown"
require_relative "legalesign/internal/type/boolean"
require_relative "legalesign/internal/type/file_input"
require_relative "legalesign/internal/type/enum"
require_relative "legalesign/internal/type/union"
require_relative "legalesign/internal/type/array_of"
require_relative "legalesign/internal/type/hash_of"
require_relative "legalesign/internal/type/base_model"
require_relative "legalesign/internal/type/base_page"
require_relative "legalesign/internal/type/request_parameters"
require_relative "legalesign/internal"
require_relative "legalesign/request_options"
require_relative "legalesign/file_part"
require_relative "legalesign/errors"
require_relative "legalesign/internal/transport/base_client"
require_relative "legalesign/internal/transport/pooled_net_requester"
require_relative "legalesign/client"
require_relative "legalesign/models/attachment_delete_params"
require_relative "legalesign/models/attachment_list_params"
require_relative "legalesign/models/attachment_list_response"
require_relative "legalesign/models/attachment_response"
require_relative "legalesign/models/attachment_retrieve_params"
require_relative "legalesign/models/attachment_upload_params"
require_relative "legalesign/models/document_archive_params"
require_relative "legalesign/models/document_create_params"
require_relative "legalesign/models/document_create_response"
require_relative "legalesign/models/document_delete_permanently_params"
require_relative "legalesign/models/document_download_audit_log_params"
require_relative "legalesign/models/document_get_fields_params"
require_relative "legalesign/models/document_get_fields_response"
require_relative "legalesign/models/document_list_params"
require_relative "legalesign/models/document_list_response"
require_relative "legalesign/models/document_preview_params"
require_relative "legalesign/models/document_retrieve_params"
require_relative "legalesign/models/document_retrieve_response"
require_relative "legalesign/models/document_status_enum"
require_relative "legalesign/models/group_create_params"
require_relative "legalesign/models/group_list_params"
require_relative "legalesign/models/group_list_response"
require_relative "legalesign/models/group_retrieve_params"
require_relative "legalesign/models/group_retrieve_response"
require_relative "legalesign/models/group_update_params"
require_relative "legalesign/models/invited_delete_params"
require_relative "legalesign/models/invited_list_params"
require_relative "legalesign/models/invited_list_response"
require_relative "legalesign/models/list_meta"
require_relative "legalesign/models/member_create_params"
require_relative "legalesign/models/member_delete_params"
require_relative "legalesign/models/member_list_params"
require_relative "legalesign/models/member_list_response"
require_relative "legalesign/models/member_response"
require_relative "legalesign/models/member_retrieve_params"
require_relative "legalesign/models/notification_list_params"
require_relative "legalesign/models/notification_list_response"
require_relative "legalesign/models/pdf_create_preview_params"
require_relative "legalesign/models/pdf_field_validation_enum"
require_relative "legalesign/models/pdf_retrieve_params"
require_relative "legalesign/models/permissions_enum"
require_relative "legalesign/models/signer_get_access_link_params"
require_relative "legalesign/models/signer_get_rejection_reason_params"
require_relative "legalesign/models/signer_get_rejection_reason_response"
require_relative "legalesign/models/signer_reset_params"
require_relative "legalesign/models/signer_retrieve_fields_params"
require_relative "legalesign/models/signer_retrieve_fields_response"
require_relative "legalesign/models/signer_retrieve_params"
require_relative "legalesign/models/signer_retrieve_response"
require_relative "legalesign/models/signer_send_reminder_params"
require_relative "legalesign/models/signer_status_enum"
require_relative "legalesign/models/status_response"
require_relative "legalesign/models/status_retrieve_all_params"
require_relative "legalesign/models/status_retrieve_all_response"
require_relative "legalesign/models/status_retrieve_params"
require_relative "legalesign/models/subscribe_create_webhook_params"
require_relative "legalesign/models/template_archive_params"
require_relative "legalesign/models/template_create_params"
require_relative "legalesign/models/template_list_params"
require_relative "legalesign/models/template_list_response"
require_relative "legalesign/models/templatepdf/field_create_params"
require_relative "legalesign/models/templatepdf/field_list_params"
require_relative "legalesign/models/templatepdf/field_list_response"
require_relative "legalesign/models/template_pdf"
require_relative "legalesign/models/templatepdf_archive_params"
require_relative "legalesign/models/templatepdf_convert_tags_params"
require_relative "legalesign/models/templatepdf_create_params"
require_relative "legalesign/models/templatepdf_get_edit_link_params"
require_relative "legalesign/models/templatepdf_get_edit_link_response"
require_relative "legalesign/models/templatepdf_list_params"
require_relative "legalesign/models/templatepdf_list_response"
require_relative "legalesign/models/templatepdf_retrieve_params"
require_relative "legalesign/models/template_retrieve_params"
require_relative "legalesign/models/template_retrieve_response"
require_relative "legalesign/models/template_update_params"
require_relative "legalesign/models/timezone_enum"
require_relative "legalesign/models/unsubscribe_delete_webhook_params"
require_relative "legalesign/models/user_create_params"
require_relative "legalesign/models/user_retrieve_params"
require_relative "legalesign/models/user_retrieve_response"
require_relative "legalesign/models/user_update_params"
require_relative "legalesign/models/webhook_event_filter_enum"
require_relative "legalesign/models"
require_relative "legalesign/resources/attachment"
require_relative "legalesign/resources/document"
require_relative "legalesign/resources/group"
require_relative "legalesign/resources/invited"
require_relative "legalesign/resources/member"
require_relative "legalesign/resources/notifications"
require_relative "legalesign/resources/pdf"
require_relative "legalesign/resources/signer"
require_relative "legalesign/resources/status"
require_relative "legalesign/resources/subscribe"
require_relative "legalesign/resources/template"
require_relative "legalesign/resources/templatepdf"
require_relative "legalesign/resources/templatepdf/fields"
require_relative "legalesign/resources/unsubscribe"
require_relative "legalesign/resources/user"
